### ISSUE TITLE
Reserving ALPN Identifiers for "ignore/"

### ISSUE THREAD

**Issue by seanturner** [tlswg/draft-ietf-tls-grease#3]
THere's a TODO for reserving "ignore/" ALPN.

**Comment by seanturner** [comment]
@davidben are you thinking:

     Protocol: ignore/1
     Identification: 0x69 0x67 0x6e 0x6f 0x72 0x65 0x31
     Reference: (This document)
     ...
     Protocol: ignore/10
     Identification: 0x69 0x67 0x6e 0x6f 0x72 0x65 0x31 0x30
     Reference: (This document)

**Comment by davidben** [comment]
I didn't have a particularly clear picture in my mind, TBH. We're not sending fake ALPN values or anything right now. ignore/[numbers] seems fine.

Or maybe it would be better to drop the "ignore/" thing and just use the same two-byte pattern. "ignore/" makes it look like you should do a prefix check, which isn't really what we want...

**Comment by seanturner** [comment]
@ekr @martinthomson @hannestschofenig @chris-wood @vasilvv @richsalz PTAL because I think this is really the last "technical" point remaining.

**Comment by richsalz** [comment]
@davidben not sure what you mean by two-byte pattern.  You mean things like "qz" "db" "r$" etc?
If so, I agree that that is better.

**Comment by davidben** [comment]
Yeah. For the sake of consistency, I figure it could just be the same old 0x?a, 0x?a pattern that everything else does. (Though they then wouldn't be ASCII. Could pick some pattern that's ASCII if that's preferred.)

**Comment by richsalz** [comment]
i think two random bytes is good (testing for non-ascii seems greasy as well)

**Comment by vasilvv** [comment]
I also prefer the two-byte pattern, since ignore/ might indicate to people that this is somehow meant to be special-cased.

**Comment by davidben** [comment]
Two bytes it is! https://github.com/tlswg/draft-ietf-tls-grease/pull/6
