### ISSUE TITLE
Fingerprinting in security considerations

### ISSUE THREAD

**Issue by jsalowey** [tlswg/draft-ietf-tls-grease#5]
A possible privacy consideration for Grease

Implementations that do not select grease values at random my open up the opportunity for the fingerprinting of implementations and may impact the privacy of users.

**Comment by davidben** [comment]
Ah yes, good point. That should be pointed out explicitly. Will put together a PR after Thanksgiving (and after #6 is merged since it contains a build fix and I'm not sure how PRs depending on pieces of other PRs works :-) ).

**Comment by seanturner** [comment]
@davidben @jsalowey @chris-wood unless there are any objections once we get this issue squared away I'll go ahead and issue a WGLC.  It's been marinating long enough.

**Comment by davidben** [comment]
Should be fixed by #8.
